Traceback (most recent call last):
  File "/home/van/Programs/miniforge3/envs/webdev/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/van/Programs/miniforge3/envs/webdev/lib/python3.11/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/van/Programs/miniforge3/envs/webdev/lib/python3.11/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/van/Programs/miniforge3/envs/webdev/lib/python3.11/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/van/Programs/miniforge3/envs/webdev/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/van/Programs/miniforge3/envs/webdev/lib/python3.11/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/van/Programs/miniforge3/envs/webdev/lib/python3.11/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/van/Programs/miniforge3/envs/webdev/lib/python3.11/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import pytraj as pt
import matplotlib.pyplot as plt

# Load trajectory
traj = pt.iterload('../test/prod.nc', top='../test/step3_pbcsetup.parm7')

# Superimpose to 1st frame and alpha carbons
pt.superpose(traj, ref=0, mask="@CA")

rmsf0 = pt.rmsf(traj, mask="@CA")

# Shade domains different color
# plt.axvspan(   1,   56, facecolor='tab:red', alpha=0.2)
# plt.axvspan( 718,  765, facecolor='tab:red', alpha=0.2)
# plt.axvspan( 925, 1102, facecolor='tab:red', alpha=0.2)
# plt.axvspan(  56,  718, facecolor='tab:blue', alpha=0.2)
# plt.axvspan( 765,  924, facecolor='tab:orange', alpha=0.2)
# plt.axvspan(1099, 1368, facecolor='tab:green', alpha=0.2)

# Plot Residue # vs RMSF
plt.plot(np.arange(1,len(rmsf0.T[0])+1), rmsf0.T[1])
plt.xlabel('Residue Number')
plt.ylabel('RMSF (Ã…)')
# plt.savefig('rmsf.png', dpi=300)

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 1[0m
[0;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[1;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mpytraj[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpt[39;00m
[1;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m

[0;31mModuleNotFoundError[0m: No module named 'numpy'
ModuleNotFoundError: No module named 'numpy'

