Traceback (most recent call last):
  File "/Users/van/Programs/miniforge3/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/van/Programs/miniforge3/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/van/Programs/miniforge3/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/van/Programs/miniforge3/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/van/Programs/miniforge3/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/van/Programs/miniforge3/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/van/Programs/miniforge3/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
n_windows=42
n_cvs=10

cvs_avg = np.zeros((n_windows, n_cvs))
cvs_std = np.zeros((n_windows, n_cvs))

for i in range(n_windows):
        fnames = sorted(glob('../%02d/d??.dat' % i))    
        arrays = [np.loadtxt(f, usecols=1)[600::] for f in fnames[:]]
        for j in range(n_cvs):
            average = np.average(arrays[j])
            std = np.std(arrays[j])
            cvs_avg[i,j] = average
            cvs_std[i,j] = std
            
cv_avg = np.transpose(cvs_avg)
cv_std = np.transpose(cvs_std)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mIndexError[0m                                Traceback (most recent call last)
Cell [0;32mIn[3], line 11[0m
[1;32m      9[0m arrays [38;5;241m=[39m [np[38;5;241m.[39mloadtxt(f, usecols[38;5;241m=[39m[38;5;241m1[39m)[[38;5;241m600[39m::] [38;5;28;01mfor[39;00m f [38;5;129;01min[39;00m fnames[:]]
[1;32m     10[0m [38;5;28;01mfor[39;00m j [38;5;129;01min[39;00m [38;5;28mrange[39m(n_cvs):
[0;32m---> 11[0m     average [38;5;241m=[39m np[38;5;241m.[39maverage([43marrays[49m[43m[[49m[43mj[49m[43m][49m)
[1;32m     12[0m     std [38;5;241m=[39m np[38;5;241m.[39mstd(arrays[j])
[1;32m     13[0m     cvs_avg[i,j] [38;5;241m=[39m average

[0;31mIndexError[0m: list index out of range

